edge(fallen_tree, pantograph).
edge(fallen_tree, overhead_line).
edge(service_table, switch).
edge(fire, overhead_line).
edge(pantograph, overhead_line).
edge(overhead_line, pantograph).
edge(switch, signal).
edge(signal, switch).
edge(overhead_line, static_inverter).
edge(static_inverter, ac).
edge(compressor, door).
edge(compressor, horn).
edge(compressor, brake).
edge(ac, series).
edge(door, series).
edge(horn, series).
edge(brake, series).
edge(traction, series).
edge(wiper, series).
edge(speedometer, series).